# IMPORTANTE: Usamos localhost porque la app corre fuera de Docker, 
# pero el puerto es el 5433 que es el que mapeaste hacia afuera.
spring.datasource.url=jdbc:postgresql://localhost:5433/attendance_db
spring.datasource.username=user
spring.datasource.password=password

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
