spring.datasource.url=jdbc:postgresql://localhost:5433/attendance_db
spring.datasource.username=admin
spring.datasource.password=password
# Esto ayudara a que Hibernate cree la tabla 'attendance' automaticamente
spring.jpa.hibernate.ddl-auto=update
