# Nombre del servicio actualizado
spring.application.name=attendance-service

# Configuracion JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Perfil activo por defecto
spring.profiles.active=local
